application: hal-web
version: 1
runtime: python27
threadsafe: true
api_version: 1

libraries:
- name: django
  version: "1.2"
  
builtins:
- datastore_admin: on

handlers:
- url: /styles
  static_dir: static_data/styles
  
- url: /images
  static_dir: static_data/images
  
- url: /jscripts
  static_dir: static_data/jscripts
  
- url: /favicon\.ico
  static_files: static_data/images/favicon.ico
  upload: StaticData/images/favicon\.ico

#Admin
- url: /admin/.*
  script: apps.admin.app
  login: admin

#TheRest
- url: /.*
  script: apps.base.app

