application: halicea-cms
version: 2
runtime: python
api_version: 1

builtins:
- datastore_admin: on

inbound_services:
- warmup

handlers:
- url: /styles
  static_dir: static_data/styles
  
- url: /styles/images
  static_dir: static_data/styles/images

- url: /images
  static_dir: static_data/images
  
- url: /jscripts
  static_dir: static_data/jscripts
  
- url: /favicon\.ico
  static_files: static_data/images/favicon.ico
  upload: StaticData/images/favicon\.ico
#Remote API
- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin  

#App Stats  
- url: /stats.*
  script: Apps/appstats.py
  login: admin
  
#Admin
- url: /admin/.*
  script: apps/admin.py
  login: admin

#TheRest
- url: /.*
  script: apps/base.py

